### ISSUE TITLE
enhancement request: retain original timestamps in zipped bags

### ISSUE THREAD

**Issue by timhutch** [avpreserve/uk-exactly#12]
I see that this is flagged as a known issue in the user guide, but a related issue (#2) was also closed, so I wanted to add a few points in the hopes that an enhancement relating to timestamps might still be on the radar.

Ideally, creation, modification and access timestamps would be retained. At least in Windows, though, creation dates are somewhat flaky (e.g. moving/copying a file will trigger a new timestamp). I haven't tested much with last access date, but creation date is arguably less reliable even on a source system. (Possibly a different matter on other operating systems, but I suspect it's no worse.)

The good news is that Exactly does already preserve the modification timestamps for UNzipped bags. But they are not retained after sftp transfer (which I realize is complicated). So a workaround is to create an unzipped bag, zip it using the built-in Windows functionality, and then transfer it independently. But having this built into Exactly would make it so much easier for working with donors.

I appreciate that FileSystemInfo.txt does capture this information, but the use case I have in mind is ingesting the bag into a preservation system (notably Archivematica) that runs characterization microservices on the files, ultimately adding the extracted date information to the METS file. (And FileSystemInfo does not seem to be ingested by Archivematica.) So ideally the correct modification date would be extracted, not the date that the bag was created.

Recording an accurate modification date is also consistent with the guidelines for the PREMIS element dateCreatedByApplication: "This is the date the object was created by the creating application, not
the date any copy was made externally or by the repository. ...The date a file is written to storage can be recorded as an Event. If the object itself contains internal creation and modification dates, the modification date should be used as dateCreatedByApplication." (https://www.loc.gov/standards/premis/v3/premis-3-0-final.pdf - page 89)

I realize that this is unlikely to be a simple fix, but I hope you will keep this under consideration.

**Comment by pvizner** [comment]
Hi Tim,

We've received your request and have added it to the list of requested features.

Thank you!

**Comment by timhutch** [comment]
Thanks, I appreciate the confirmation.
